name: shell commands
push

on:
job: 
  run-shell-commands:
   run-on: ubuntu-latest
   steps:
     -name: echo string
      run:  echo "hello"

     -name: multi line string
      run: |
       pwd
       ls
       node -v
       ls -a
      -name: python command
       run:
          import platform
          print(platform.processor())
        shell: python